import type {
  Movement,
  MovementContext,
  MovementFamilyId,
  MovementRestrictions,
} from "./types";

const ALL_TRAINING_CONTEXTS: MovementContext[] = [
  "warmup",
  "primary",
  "secondary",
  "skill",
  "accessory",
];

const CONDITIONING_CONTEXTS: MovementContext[] = ["warmup", "conditioning"];

function movement(
  value: Omit<Movement, "purposes" | "prerequisites" | "unilateral"> & {
    purposes?: string[];
    prerequisites?: string[];
    unilateral?: boolean;
  },
): Movement {
  return {
    purposes: [],
    prerequisites: [],
    unilateral: false,
    ...value,
  };
}

export const MOVEMENT_FAMILIES: ReadonlyArray<{
  id: MovementFamilyId;
  name: string;
}> = Object.freeze([
  { id: "front_squat", name: "Front squat" },
  { id: "back_squat", name: "Back squat" },
  { id: "hinge", name: "Hinge" },
  { id: "horizontal_press", name: "Horizontal press" },
  { id: "vertical_press", name: "Vertical press" },
  { id: "strict_pull", name: "Strict pull" },
  { id: "kipping_pull", name: "Kipping pull" },
  { id: "toes_to_bar", name: "Toes to bar" },
  { id: "bar_muscle_up", name: "Bar muscle-up" },
  { id: "ring_muscle_up", name: "Ring muscle-up" },
  { id: "handstand", name: "Handstand" },
  { id: "snatch", name: "Snatch" },
  { id: "clean", name: "Clean" },
  { id: "jerk", name: "Jerk" },
  { id: "clean_and_jerk", name: "Clean and jerk" },
  { id: "running", name: "Running" },
  { id: "rowing", name: "Rowing" },
  { id: "bike", name: "Bike" },
  { id: "ski", name: "Ski" },
  { id: "carry", name: "Carry" },
  { id: "core", name: "Core" },
  { id: "jumping", name: "Jumping" },
  { id: "burpee", name: "Burpee" },
  { id: "accessory", name: "Accessory" },
]);

export const MOVEMENTS: ReadonlyArray<Movement> = Object.freeze([
  movement({
    id: "front_squat",
    name: "Front squat",
    familyId: "front_squat",
    category: "strength",
    difficulty: "intermediate",
    allowedContexts: ["primary", "secondary"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell", "rack"],
    secondsPerRep: 4,
    purposes: ["squat strength", "upright trunk strength"],
  }),
  movement({
    id: "back_squat",
    name: "Back squat",
    familyId: "back_squat",
    category: "strength",
    difficulty: "intermediate",
    allowedContexts: ["primary", "secondary"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell", "rack"],
    secondsPerRep: 4,
    purposes: ["lower-body strength"],
  }),
  movement({
    id: "muscle_snatch",
    name: "Muscle snatch",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["warmup", "secondary", "skill"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 6,
    isTechniqueDrill: true,
    purposes: ["turnover timing", "bar path"],
  }),
  movement({
    id: "hang_power_snatch",
    name: "Hang power snatch",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["primary", "secondary", "skill", "conditioning"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 7,
    purposes: ["extension timing", "fast turnover"],
  }),
  movement({
    id: "hang_squat_snatch",
    name: "Hang squat snatch",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "advanced",
    allowedContexts: ["primary", "secondary", "skill"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 8,
    purposes: ["receiving position", "positional strength"],
  }),
  movement({
    id: "squat_snatch",
    name: "Squat snatch",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "advanced",
    allowedContexts: ["primary", "secondary", "skill"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 8,
    purposes: ["full-lift coordination"],
  }),
  movement({
    id: "snatch",
    name: "Snatch",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "advanced",
    allowedContexts: ["primary", "secondary", "skill"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 8,
    purposes: ["competition-lift development"],
  }),
  movement({
    id: "snatch_pull",
    name: "Snatch pull",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["primary", "secondary", "accessory"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 6,
    purposes: ["snatch-specific pulling strength"],
  }),
  movement({
    id: "clean_pull",
    name: "Clean pull",
    familyId: "clean",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["primary", "secondary", "accessory"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 6,
    purposes: ["clean-specific pulling strength"],
  }),
  movement({
    id: "hang_clean_and_jerk",
    name: "Hang clean plus jerk",
    familyId: "clean_and_jerk",
    category: "olympic_lifting",
    difficulty: "advanced",
    allowedContexts: ["primary", "secondary", "skill", "conditioning"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 12,
    purposes: ["clean timing", "overhead consistency"],
  }),
  movement({
    id: "clean_and_jerk",
    name: "Clean and jerk",
    familyId: "clean_and_jerk",
    category: "olympic_lifting",
    difficulty: "advanced",
    allowedContexts: ["primary", "secondary", "skill"],
    loadable: true,
    requiresPercentageReference: true,
    equipment: ["barbell"],
    secondsPerRep: 12,
    purposes: ["competition-lift development"],
  }),
  movement({
    id: "strict_pull_up",
    name: "Strict pull-up",
    familyId: "strict_pull",
    category: "gymnastics",
    difficulty: "intermediate",
    allowedContexts: ["secondary", "skill", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["pull-up bar"],
    secondsPerRep: 4,
    purposes: ["strict pulling capacity"],
  }),
  movement({
    id: "ring_row",
    name: "Ring row",
    familyId: "strict_pull",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["warmup", "secondary", "skill", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["rings"],
    secondsPerRep: 3,
    purposes: ["strict-pull scaling"],
  }),
  movement({
    id: "hollow_hold",
    name: "Hollow hold",
    familyId: "core",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["warmup", "secondary", "skill", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 1,
    isIsometric: true,
    purposes: ["midline shape"],
  }),
  movement({
    id: "arch_hold",
    name: "Arch hold",
    familyId: "core",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["warmup", "secondary", "skill", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 1,
    isIsometric: true,
    purposes: ["posterior body shape"],
  }),
  movement({
    id: "hanging_knee_raise",
    name: "Hanging knee raise",
    familyId: "toes_to_bar",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["secondary", "skill", "accessory", "conditioning"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["pull-up bar"],
    secondsPerRep: 3,
    purposes: ["hanging midline control"],
  }),
  movement({
    id: "romanian_deadlift",
    name: "Romanian deadlift",
    familyId: "hinge",
    category: "accessory",
    difficulty: "intermediate",
    allowedContexts: ["accessory"],
    loadable: true,
    requiresPercentageReference: false,
    equipment: ["barbell"],
    secondsPerRep: 4,
    purposes: ["posterior-chain strength"],
  }),
  movement({
    id: "reverse_lunge",
    name: "Reverse lunge",
    familyId: "accessory",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["accessory"],
    loadable: true,
    requiresPercentageReference: false,
    equipment: ["dumbbell"],
    secondsPerRep: 3,
    unilateral: true,
    purposes: ["single-leg strength"],
  }),
  movement({
    id: "farmer_carry",
    name: "Farmer carry",
    familyId: "carry",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["accessory", "conditioning"],
    loadable: true,
    requiresPercentageReference: false,
    equipment: ["dumbbell"],
    secondsPerRep: 1,
    purposes: ["grip and trunk capacity"],
  }),
  movement({
    id: "dead_bug",
    name: "Dead bug",
    familyId: "core",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["warmup", "accessory", "cooldown"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 3,
    purposes: ["trunk control"],
  }),
  movement({
    id: "side_plank",
    name: "Side plank",
    familyId: "core",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["accessory", "cooldown"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 1,
    isIsometric: true,
    purposes: ["lateral trunk endurance"],
  }),
  movement({
    id: "band_face_pull",
    name: "Band face pull",
    familyId: "accessory",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["warmup", "accessory", "cooldown"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["band"],
    secondsPerRep: 2,
    purposes: ["shoulder health"],
  }),
  movement({
    id: "run",
    name: "Run",
    familyId: "running",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: CONDITIONING_CONTEXTS,
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 1,
  }),
  movement({
    id: "row",
    name: "Row",
    familyId: "rowing",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: CONDITIONING_CONTEXTS,
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["rower"],
    secondsPerRep: 1,
  }),
  movement({
    id: "bike",
    name: "Bike",
    familyId: "bike",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: CONDITIONING_CONTEXTS,
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["bike"],
    secondsPerRep: 1,
  }),
  movement({
    id: "ski",
    name: "Ski",
    familyId: "ski",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: CONDITIONING_CONTEXTS,
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["ski erg"],
    secondsPerRep: 1,
  }),
  movement({
    id: "burpee",
    name: "Burpee",
    familyId: "burpee",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: ["warmup", "conditioning"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 4,
  }),
  movement({
    id: "box_step_up",
    name: "Box step-up",
    familyId: "jumping",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: ["warmup", "conditioning"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["box"],
    secondsPerRep: 3,
  }),
  movement({
    id: "air_squat",
    name: "Air squat",
    familyId: "front_squat",
    category: "conditioning",
    difficulty: "beginner",
    allowedContexts: ["warmup", "conditioning"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 2,
  }),
  movement({
    id: "push_up",
    name: "Push-up",
    familyId: "horizontal_press",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["warmup", "conditioning", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 3,
  }),
  movement({
    id: "pvc_pass_through",
    name: "PVC pass-through",
    familyId: "accessory",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["warmup"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["PVC"],
    secondsPerRep: 2,
  }),
  movement({
    id: "empty_bar_overhead_squat",
    name: "Empty-bar overhead squat",
    familyId: "snatch",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["warmup", "skill"],
    loadable: true,
    requiresPercentageReference: false,
    equipment: ["barbell"],
    secondsPerRep: 4,
    isTechniqueDrill: true,
  }),
  movement({
    id: "empty_bar_clean_and_jerk",
    name: "Empty-bar clean and jerk",
    familyId: "clean_and_jerk",
    category: "olympic_lifting",
    difficulty: "intermediate",
    allowedContexts: ["warmup", "skill"],
    loadable: true,
    requiresPercentageReference: false,
    equipment: ["barbell"],
    secondsPerRep: 8,
    isTechniqueDrill: true,
  }),
  movement({
    id: "glute_bridge",
    name: "Glute bridge",
    familyId: "hinge",
    category: "accessory",
    difficulty: "beginner",
    allowedContexts: ["warmup", "accessory"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: [],
    secondsPerRep: 2,
  }),
  movement({
    id: "scapular_pull_up",
    name: "Scapular pull-up",
    familyId: "strict_pull",
    category: "gymnastics",
    difficulty: "beginner",
    allowedContexts: ["warmup", "skill"],
    loadable: false,
    requiresPercentageReference: false,
    equipment: ["pull-up bar"],
    secondsPerRep: 2,
  }),
]);

const MOVEMENT_BY_ID = new Map(MOVEMENTS.map((item) => [item.id, item]));

export function getMovement(movementId: string): Movement | null {
  return MOVEMENT_BY_ID.get(movementId) ?? null;
}

export function movementAllowed(
  movementId: string,
  context: MovementContext,
  equipment: string[],
  restrictions: MovementRestrictions,
): boolean {
  const item = getMovement(movementId);
  if (!item || !item.allowedContexts.includes(context)) return false;
  if (restrictions.movementIds.includes(item.id)) return false;
  if (restrictions.movementFamilyIds.includes(item.familyId)) return false;
  const available = new Set(equipment.map((value) => value.toLowerCase()));
  return item.equipment.every(
    (required) =>
      required === "" ||
      available.has(required.toLowerCase()) ||
      (required === "PVC" &&
        (available.has("pvc") || available.has("barbell"))),
  );
}

export function movementsForFamily(
  familyId: MovementFamilyId,
  context: MovementContext,
  equipment: string[],
  restrictions: MovementRestrictions,
): Movement[] {
  return MOVEMENTS.filter(
    (item) =>
      item.familyId === familyId &&
      movementAllowed(item.id, context, equipment, restrictions),
  );
}

export function assertCatalogIntegrity(): string[] {
  const issues: string[] = [];
  const familyIds = new Set(MOVEMENT_FAMILIES.map((item) => item.id));
  const movementIds = new Set<string>();
  for (const item of MOVEMENTS) {
    if (movementIds.has(item.id)) issues.push(`Duplicate movement ${item.id}`);
    movementIds.add(item.id);
    if (!familyIds.has(item.familyId)) {
      issues.push(`Unknown family ${item.familyId} for ${item.id}`);
    }
    if (!item.allowedContexts.length) {
      issues.push(`No allowed contexts for ${item.id}`);
    }
  }
  return issues;
}

export const TRAINING_CONTEXTS = Object.freeze(ALL_TRAINING_CONTEXTS);
